### ISSUE TITLE
chown: cannot access '/box': No such file or directory

### ISSUE THREAD

**Issue by nimatrazmjo** [judge0/judge0#325]
using docker compose it runs successfully, however, if I want to run a code inside http://localhost:2358/dummy-client.html it gives me following error.

```
[Request 2/22/2022, 6:22:17 PM] POST http://localhost:2358/submissions?base64_encoded=true&wait=true
{
    "source_code": "I2luY2x1ZGUgPHN0ZGlvLmg+CgppbnQgbWFpbih2b2lkKSB7CiAgY2hhciBuYW1lWzEwXTsKICBzY2FuZigiJXMiLCBuYW1lKTsKICBwcmludGYoImhlbGxvLCAlc1xuIiwgbmFtZSk7CiAgcmV0dXJuIDA7Cn0=",
    "language_id": "50",
    "number_of_runs": null,
    "stdin": "SnVkZ2Uw",
    "expected_output": null,
    "cpu_time_limit": null,
    "cpu_extra_time": null,
    "wall_time_limit": null,
    "memory_limit": null,
    "stack_limit": null,
    "max_processes_and_or_threads": null,
    "enable_per_process_and_thread_time_limit": null,
    "enable_per_process_and_thread_memory_limit": null,
    "max_file_size": null,
    "enable_network": null
}
[Response 2/22/2022, 6:22:17 PM] 201 Created
{
    "stdout": null,
    "time": null,
    "memory": null,
    "stderr": null,
    "token": "536b8586-1976-49e7-ac40-7229c97c40c3",
    "compile_output": null,
    "message": "Tm8gc3VjaCBmaWxlIG9yIGRpcmVjdG9yeSBAIHJiX3N5c29wZW4gLSAvYm94\nL21haW4uYw==\n",
    "status": {
        "id": 13,
        "description": "Internal Error"
    }
}

[DONE 2/22/2022, 6:22:17 PM]



```

docker container logs

```
server_1            | D, [2022-02-22T13:52:17.140781 #40] DEBUG -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [ActiveJob] [IsolateJob] [01fa637c-ddee-4ec7-8138-5634f05055c9]    (34.3ms)  COMMIT
server_1            | Failed to create control group /sys/fs/cgroup/memory/box-9/: No such file or directory
server_1            | D, [2022-02-22T13:52:17.235925 #40] DEBUG -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [ActiveJob] [IsolateJob] [01fa637c-ddee-4ec7-8138-5634f05055c9]    (0.4ms)  BEGIN
server_1            | D, [2022-02-22T13:52:17.238995 #40] DEBUG -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [ActiveJob] [IsolateJob] [01fa637c-ddee-4ec7-8138-5634f05055c9]   Submission Update (0.6ms)  UPDATE "submissions" SET "status_id" = $1, "finished_at" = $2, "message" = $3 WHERE "submissions"."id" = $4  [["status_id", 13], ["finished_at", "2022-02-22 13:52:17.235323"], ["message", "No such file or directory @ rb_sysopen - /box/main.c"], ["id", 9]]
server_1            | D, [2022-02-22T13:52:17.240268 #40] DEBUG -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [ActiveJob] [IsolateJob] [01fa637c-ddee-4ec7-8138-5634f05055c9]    (0.9ms)  COMMIT
server_1            | chown: cannot access '/box': No such file or directory
server_1            | I, [2022-02-22T13:52:17.321153 #40]  INFO -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [ActiveJob] [IsolateJob] [01fa637c-ddee-4ec7-8138-5634f05055c9] Performed IsolateJob (Job ID: 01fa637c-ddee-4ec7-8138-5634f05055c9) from Resque(1.13.0) in 222.63ms
server_1            | D, [2022-02-22T13:52:17.325177 #40] DEBUG -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be]   Submission Load (0.6ms)  SELECT  "submissions".* FROM "submissions" WHERE "submissions"."id" = $1 LIMIT $2  [["id", 9], ["LIMIT", 1]]
server_1            | I, [2022-02-22T13:52:17.326819 #40]  INFO -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] [active_model_serializers] Rendered SubmissionSerializer with ActiveModelSerializers::Adapter::Attributes (0.75ms)
server_1            | I, [2022-02-22T13:52:17.327044 #40]  INFO -- : [d86ec78e-3cab-4d57-b09c-8f65d1f263be] Completed 201 Created in 273ms (Views: 1.3ms | ActiveRecord: 73.9ms)
workers_1           | resque-scheduler: [INFO] 2022-02-22T13:53:31+00:00: Master scheduler
workers_1           | resque-scheduler: [INFO] 2022-02-22T13:53:31+00:00: Reloading Schedule
workers_1           | resque-scheduler: [INFO] 2022-02-22T13:53:31+00:00: Loading Schedule
workers_1           | resque-scheduler: [INFO] 2022-02-22T13:53:31+00:00: Schedule empty! Set Resque.schedule
workers_1           | resque-scheduler: [INFO] 2022-02-22T13:53:31+00:00: Schedules Loaded
```

**Comment by jothiprakashv** [comment]
Same error here. Server - Ubuntu 18.04
Its working fine on  Ubuntu 16.04 and 20.04

**Comment by hermanzdosilovic** [comment]
This is probably because Ubuntu 18.04 has cgroups v2 and we are currently using isolate (sandboxing environment) that works with cgroups v1. See [Tips and Tricks](https://wiki.archlinux.org/title/cgroups) at the end of the page.

**Comment by nimatrazmjo** [comment]
I am using on mac,  it shouldn't have problem because I am using the dockerized version

**Comment by nimatrazmjo** [comment]
@hermanzdosilovic MacOS Monterey
Docker version: Docker version 20.10.11, build dea9396

**Comment by nimatrazmjo** [comment]
@hermanzdosilovic , any update on the above issue

**Comment by ahmadhaidarahmad** [comment]
@hermanzdosilovic , I’m facing the same
Issue, any help would be appreciated thank you 🙏

**Comment by nimatrazmjo** [comment]
It gives me the above error on  Mac OS Montery.

I have switched to ubuntu 18.04, and it works fine.

**Comment by FlowerWrong** [comment]
For docker desktop.

> Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.

I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.

```bash
vim ~/Library/Group\ Containers/group.com.docker/settings.json
# append "deprecatedCgroupv1": true
```

**Comment by sagardesai90** [comment]
Any update on this btw? Am seeing the same issue, with Mac on apple silicon.

**Comment by FlowerWrong** [comment]
> > For docker desktop.
> > > Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.
> > 
> > 
> > I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.
> > ```shell
> > vim ~/Library/Group\ Containers/group.com.docker/settings.json
> > # append "deprecatedCgroupv1": true
> > ```
> 
> does this work on Mac?

yes, it is for mac docker desktop.

**Comment by sagardesai90** [comment]
> > > For docker desktop.
> > > > Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.
> > > 
> > > 
> > > I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.
> > > ```shell
> > > vim ~/Library/Group\ Containers/group.com.docker/settings.json
> > > # append "deprecatedCgroupv1": true
> > > ```
> > 
> > 
> > does this work on Mac?
> 
> yes, it is for mac docker desktop.

There was a field for deprecatedCgroupv1 already and it was set to false, so I changed it to true and saved the file. Still seeing the issue though.

**Comment by FlowerWrong** [comment]
> > > > For docker desktop.
> > > > > Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.
> > > > 
> > > > 
> > > > I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.
> > > > ```shell
> > > > vim ~/Library/Group\ Containers/group.com.docker/settings.json
> > > > # append "deprecatedCgroupv1": true
> > > > ```
> > > 
> > > 
> > > does this work on Mac?
> > 
> > 
> > yes, it is for mac docker desktop.
> 
> There was a field for deprecatedCgroupv1 already and it was set to false, so I changed it to true and saved the file. Still seeing the issue though.

I used it just now. it still works fine.
```
MacBook Pro with Intel Core i7
Docker Desktop 4.6.1 (76265)
```

**Comment by sagardesai90** [comment]
> > > > > For docker desktop.
> > > > > > Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.
> > > > > 
> > > > > 
> > > > > I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.
> > > > > ```shell
> > > > > vim ~/Library/Group\ Containers/group.com.docker/settings.json
> > > > > # append "deprecatedCgroupv1": true
> > > > > ```
> > > > 
> > > > 
> > > > does this work on Mac?
> > > 
> > > 
> > > yes, it is for mac docker desktop.
> > 
> > 
> > There was a field for deprecatedCgroupv1 already and it was set to false, so I changed it to true and saved the file. Still seeing the issue though.
> 
> I used it just now. it still works fine.
> 
> ```
> MacBook Pro with Intel Core i7
> Docker Desktop 4.6.1 (76265)
> ```

Do I need to recompile or do anything after changing the settings.json file?

**Comment by FlowerWrong** [comment]
> > > > > > For docker desktop.
> > > > > > > Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.
> > > > > > 
> > > > > > 
> > > > > > I am using [deprecatedCgroupv1](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-3) option, and it works fine.
> > > > > > ```shell
> > > > > > vim ~/Library/Group\ Containers/group.com.docker/settings.json
> > > > > > # append "deprecatedCgroupv1": true
> > > > > > ```
> > > > > 
> > > > > 
> > > > > does this work on Mac?
> > > > 
> > > > 
> > > > yes, it is for mac docker desktop.
> > > 
> > > 
> > > There was a field for deprecatedCgroupv1 already and it was set to false, so I changed it to true and saved the file. Still seeing the issue though.
> > 
> > 
> > I used it just now. it still works fine.
> > ```
> > MacBook Pro with Intel Core i7
> > Docker Desktop 4.6.1 (76265)
> > ```
> 
> Do I need to recompile or do anything after changing the settings.json file? Just tried via postman and saw this: "message": "No such file or directory @ rb_sysopen - /box/script.py",

Of course you need, you need to rebuild the docker container named [judge0/compilers:1.4.0](https://github.com/judge0/judge0/blob/master/Dockerfile#L1).
See https://github.com/judge0/compilers

**Comment by WardaBoussayed** [comment]
> http://localhost:2358/dummy-client.html

Hi @sagardesai90 , did the deprecatedCgroupeV1 update solved the issue for you ?

**Comment by hermanzdosilovic** [comment]
I can confirm that the following solution that @sagardesai90 proposed works.

**OS**:
- **Version**: macOS Big Sur (version: 11.6.6)
- **Processor**: 2.6 GHz 6-Core Intel Core i7

**Docker Desktop**:
- **Version**: 4.8.2 (79419)
- **Engine**: 20.10.14
- **Compose**: v2.5.1

As @sagardesai90 I have opened file `~/Library/Group\ Containers/group.com.docker/settings.json` with `vim`:
```
vim ~/Library/Group\ Containers/group.com.docker/settings.json
```

Then I found the `deprecatedCgroupv1` option and changed it from `false` to `true`.

Finally, I have restarted Docker Desktop.

Thank you @sagardesai90.

**Comment by Axel546** [comment]
Still doesn't work for macos on silicon cpu

**Comment by Harsh4999** [comment]
> This is probably because Ubuntu 18.04 has cgroups v2 and we are currently using isolate (sandboxing environment) that works with cgroups v1. See [Tips and Tricks](https://wiki.archlinux.org/title/cgroups) at the end of the page.

It works for Arch Linux too I passed this arg in kernel param during boot = systemd.unified_cgroup_hierarchy=0

**Comment by neolee** [comment]
> It works for Arch Linux too I passed this arg in kernel param during boot = systemd.unified_cgroup_hierarchy=0

I'm running the docker version of judge0 on Arch Linux and get the same error as seen in this thread, so judge0 do not support cgroup v2 and I should modify kernel parameter to fallback to v1 right?

**Comment by sahil-bansal-sb** [comment]
I'm facing same issue on Ubuntu 22.04 as well
Following are the docker versions
```
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 OS/Arch:           linux/amd64

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  OS/Arch:          linux/amd64
 containerd:
  Version:          1.6.15
 runc:
  Version:          1.1.4
 docker-init:
  Version:          0.19.0
  ```

Please suggest

**Comment by mekterovic** [comment]
You need to fallback to groups v1, here is how I did it on Ubuntu 22:
````
sudo nano /etc/default/grub
# edit this line, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo update-grub
sudo reboot
````
Cheers

**Comment by tsenguunchik** [comment]
I have apple M2 chip and having this issue. Any updates?

**Comment by agulencina96** [comment]
> You need to fallback to groups v1, here is how I did it on Ubuntu 22:
> 
> ```
> sudo nano /etc/default/grub
> # edit this line, and save:
> GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> sudo update-grub
> sudo reboot
> ```
> 
> Cheers

works for Ubuntu 22.04 ty❤️

**Comment by HarjasSodhi** [comment]
@Axel546 were you able to get it to work on m1? i am facing the same issue

**Comment by pendi1901** [comment]
I've changed the deprecatedCgroupv1 from false to true but still doesn't seem to work. I work on m1 as well

**Comment by projectninjatech** [comment]
> > You need to fallback to groups v1, here is how I did it on Ubuntu 22:
> > ```
> > sudo nano /etc/default/grub
> > # edit this line, and save:
> > GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> > sudo update-grub
> > sudo reboot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers
> 
> works for Ubuntu 22.04 ty❤️

This works on Oracle Server Ubuntu 22.04

**Comment by sujitroy-dev** [comment]
> I've changed the deprecatedCgroupv1 from false to true but still doesn't seem to work. I work on m1 as well

i'm also using macbook air m1, this worked for me.

1.`vim ~/Library/Group\ Containers/group.com.docker/settings.json`
2.`append "deprecatedCgroupv1": true`
3.`sudo pkill Docker`
4.`open /Applications/Docker.app`
```
//5.  do this with all containers related to judge0
docker restart [containerID]
```

**Comment by sahilpahuja963** [comment]
> This is probably because Ubuntu 18.04 has cgroups v2 and we are currently using isolate (sandboxing environment) that works with cgroups v1. See [Tips and Tricks](https://wiki.archlinux.org/title/cgroups) at the end of the page.

sandbox has updated to cgroup2 recently. Can we expect an update?

**Comment by farhank5023** [comment]
> You need to fallback to groups v1, here is how I did it on Ubuntu 22:
> 
> ```
> sudo nano /etc/default/grub
> # edit this line, and save:
> GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> sudo update-grub
> sudo reboot
> ```
> 
> Cheers

works !!! thankyou

**Comment by CurtisDeCastro** [comment]
```
sudo nano /etc/default/grub
# add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo update-grub
sudo reboot
```

worked for me as well on Amazon Linux

**Comment by DhanushNehru** [comment]
The  `sudo update-grub` command didn't work in Amazon Linux

But the below code worked

```
sudo nano /etc/default/grub
#  add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
sudo reboot
```

And the code got executed successfully ⭐️

**Comment by DhanushNehru** [comment]
The  `sudo update-grub` command didn't work for me in Amazon Linux

But the below steps worked

```
sudo nano /etc/default/grub
#  add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
sudo reboot
```

And the code got executed successfully ⭐️

**Comment by HansLanda14ib** [comment]
I added the line but still problem occured

![image](https://github.com/judge0/judge0/assets/100965812/196763d7-9a9d-432d-b927-bec7d11a09bf)

**Comment by kishanRidgeant** [comment]
`sudo nano /etc/default/grub
# add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo update-grub
sudo reboot`

i have configured this properly on my linux 22.04 but when i hit the endpoint it gives me error as show in below screenshot


![Screenshot from 2024-05-15 15-48-33](https://github.com/judge0/judge0/assets/146085996/9623c50f-d861-4dce-b6db-c923753ea459)

**Comment by vr2432** [comment]
I got the same error too. Any solutions

**Comment by keshav2003garg** [comment]
Any solution yet?

**Comment by Kagenui-yozuru** [comment]
debian 12.5
```
sudo nano /etc/default/grub
# add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo update-grub
sudo reboot
```
It's work .Cheers!

**Comment by nithishelplusplus** [comment]
I am using kubernatics fom digital ocean any specific instructions for me facing the same issue.......

**Comment by olegkvasov** [comment]
For those with macOS and Docker Desktop above 4.34 - a solution will help you out https://github.com/judge0/judge0/issues/525

**Comment by charles-wangkai** [comment]
The issue happens again with Docker Desktop for macOS 4.38.0, while changing to cgroup v1 works with old version 4.37.2. It would be better for judge0 to adapt to cgroup v2 soon.

**Comment by DhanushNehru** [comment]
@narayanann This is the one I tried, and it worked. https://github.com/judge0/judge0/issues/325#issuecomment-2058554238


Currently I am not working on it and I have did judge0 setup in my opensource project feel free to check it [Code Editor Built Using Judge0](https://github.com/DhanushNehru/CustomCodeEditor), which is on a working condition.

**Comment by acrossoffwest** [comment]
> For those with macOS and Docker Desktop above 4.34 - a solution will help you out [#525](https://github.com/judge0/judge0/issues/525)

it worked out well

**Comment by olegkvasov** [comment]
> > For those with macOS and Docker Desktop above 4.34 - a solution will help you out [#525](https://github.com/judge0/judge0/issues/525)
> 
> it worked out well

I confirm that it stopped working on v4.38.

**Comment by Justtyn** [comment]
在dockerv4.38中即使修改为cgroupv1也并不生效 请尽快修复这个问题 🙏

**Comment by Aman0413** [comment]
[{"stdout":null,"time":null,"memory":null,"stderr":null,"token":"9f8b93a3-afc0-4072-a221-b169e4133078","compile_output":null,"message":"No such file or directory @ rb_sysopen - /box/main.cpp","status":{"id":13,"description":"Internal Error"}}](url)


Getting this when I submit the code. 
I am using Macbook Air M1 mac os sequoia 15.3.2

**Comment by LeAnhTu-Github** [comment]
@Aman0413  I have the same problem as you, have you found a fix yet?

**Comment by Justtyn** [comment]
> [@Aman0413](https://github.com/Aman0413) 我遇到了和你同样的问题，你找到解决办法了吗？

You can downgrade the version of docker desktop to v4.37, which can solve the problem. I successfully ran it on macbook m2.

**Comment by Aman0413** [comment]
> > [@Aman0413](https://github.com/Aman0413) 我遇到了和你同样的问题，你找到解决办法了吗？
> 
> You can downgrade the version of docker desktop to v4.37, which can solve the problem. I successfully ran it on macbook m2.

I have installed Docker Desktop version v4.32.0. But the problem is same, it is not working. Could you please give me step by step procedure to run this ?

**Comment by LeAnhTu-Github** [comment]
@Aman0413 
I fixed it:
- first go to docker's setting.json file with the command:
nano ~/Library/Group\ Containers/group.com.docker/settings.json
- Second: force docker to use Cgroup v1 version by pasting the following json:
{
"deprecatedCgroupv1": true,
"useVirtualizationFramework": false,
"vpnKitMaxPortIdleTime": 300,
"linuxVM": {
"cgroupVersion": 1
}
}
then you save it and restart the docker server

**Comment by LeAnhTu-Github** [comment]
@Aman0413 
I fixed it:
- first go to docker's setting.json file with the command:
nano ~/Library/Group\ Containers/group.com.docker/settings.json
- Second: force docker to use Cgroup v1 version by pasting the following json:
{
"deprecatedCgroupv1": true,
"useVirtualizationFramework": false,
"vpnKitMaxPortIdleTime": 300,
"linuxVM": {
"cgroupVersion": 1
}
}
then you save it and restart the docker server

**Comment by Aman0413** [comment]
> [@Aman0413](https://github.com/Aman0413) I fixed [it:]()
> 
> * first go to docker's setting.json file with the command:
>   nano ~/Library/Group\ Containers/group.com.docker/settings.json
> * Second: force docker to use Cgroup v1 version by pasting the following json:
>   {
>   "deprecatedCgroupv1": true,
>   "useVirtualizationFramework": false,
>   "vpnKitMaxPortIdleTime": 300,
>   "linuxVM": {
>   "cgroupVersion": 1
>   }
>   }
>   then you save it and restart the docker server

I did same all as mentioned. But new error comes. I have set postgres password.

<img width="1263" alt="Image" src="https://github.com/user-attachments/assets/d04d8aa4-1786-4880-899d-8ce1ce326666" />

<img width="1271" alt="Image" src="https://github.com/user-attachments/assets/21d22a12-ace0-45c5-aacd-2f2d7bd14660" />

**Comment by binh1922004** [comment]
> > [@Aman0413](https://github.com/Aman0413) I fixed it:
> > 
> > * first go to docker's setting.json file with the command:
> >   nano ~/Library/Group\ Containers/group.com.docker/settings.json
> > * Second: force docker to use Cgroup v1 version by pasting the following json:
> >   {
> >   "deprecatedCgroupv1": true,
> >   "useVirtualizationFramework": false,
> >   "vpnKitMaxPortIdleTime": 300,
> >   "linuxVM": {
> >   "cgroupVersion": 1
> >   }
> >   }
> >   then you save it and restart the docker server
> 
> I did same all as mentioned. But new error comes. I have set postgres password.
> 
> <img alt="Image" width="1263" src="https://private-user-images.githubusercontent.com/82309980/427817332-d04d8aa4-1786-4880-899d-8ce1ce326666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIyOTg3MjUsIm5iZiI6MTc1MjI5ODQyNSwicGF0aCI6Ii84MjMwOTk4MC80Mjc4MTczMzItZDA0ZDhhYTQtMTc4Ni00ODgwLTg5OWQtOGNlMWNlMzI2NjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEyVDA1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzFkZjNlMWYwYWNiNTgzMWQ3ZDZmNGYwNmFlNTEwOTE4MDkxOGUxNWVmZDk1ODQ5NGFhNGVjMWFjMjgwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7NJ7s3JxF8Cn6DeTupjLApg2xJLtA-6bK2wVZTkFZ4w"> <img alt="Image" width="1271" src="https://private-user-images.githubusercontent.com/82309980/427817425-21d22a12-ace0-45c5-aacd-2f2d7bd14660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIyOTg3MjUsIm5iZiI6MTc1MjI5ODQyNSwicGF0aCI6Ii84MjMwOTk4MC80Mjc4MTc0MjUtMjFkMjJhMTItYWNlMC00NWM1LWFhY2QtMmYyZDdiZDE0NjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEyVDA1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkN2U4YjQ0ZjY0MGFiNjhiOTU3N2RiNmUyZmNmMTJmNjA3MGRhMzM1NzBjMWRiODEwYzAxOWVmYTBlZDMyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BXZJQayeCDJAXv_OmEZpCYafdBE_IKE4BPIeX0PktJM">

@Aman0413 Now, can u fix that issue?

**Comment by krishnapaljadeja** [comment]
I tried everything and still can't make this work , can anybody help me with this ? (there is no cgroup v1  when i try to check the cgroups in system , only cgroup 2 is shown
 )

**Comment by binh1922004** [comment]
> I tried everything and still can't make this work , can anybody help me with this ? (there is no cgroup v1 when i try to check the cgroups in system , only cgroup 2 is shown)

What docker verision, OS are you using?

**Comment by Gopal-nd** [comment]
same error

**Comment by binh1922004** [comment]
If you are using Macos, you can check my solution in [this](https://github.com/judge0/judge0/issues/552#issuecomment-3078835003)

**Comment by Gopal-nd** [comment]
> If you are using Macos, you can check my solution in [this](https://github.com/judge0/judge0/issues/552#issuecomment-3078835003)

I am using Ubuntu 24.04.2 LTS

**Comment by binh1922004** [comment]
> > If you are using Macos, you can check my solution in [this](https://github.com/judge0/judge0/issues/552#issuecomment-3078835003)
> 
> I am using Ubuntu 24.04.2 LTS

I used to use ubuntu 22.04 and resolved this error. You can try:

```
sudo nano /etc/default/grub
# add this line at the top, and save:
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
sudo update-grub
sudo reboot
```

**Comment by Gopal-nd** [comment]
> > > If you are using Macos, you can check my solution in [this](https://github.com/judge0/judge0/issues/552#issuecomment-3078835003)
> > 
> > 
> > I am using Ubuntu 24.04.2 LTS
> 
> I used to use ubuntu 22.04 and resolved this error. You can try:
> 
> ```
> sudo nano /etc/default/grub
> # add this line at the top, and save:
> GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> sudo update-grub
> sudo reboot
> ```

<img width="806" height="309" alt="Image" src="https://github.com/user-attachments/assets/4d0822fd-9d69-4ebf-9a80-f4545798cfe0" />
still not working

**Comment by yipfram** [comment]
@nimatrazmjo  Could you reopen the issue?

**Comment by yipfram** [comment]
@yipfram OK, i'll open an other one then
